"""baseline_schema

Revision ID: 001_baseline
Revises: 
Create Date: 2026-08-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables for LeadStreamAI baseline schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsheet_sync_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sheet_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_auto_sync', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gsheet_sync_configs_pkey'))
    )
    op.create_table('family_offices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strategic_fit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_synced', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('family_offices_pkey')),
    sa.UniqueConstraint('name', name=op.f('family_offices_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('owner_username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prompts_pkey'))
    )
    op.create_table('leads_raw',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persona', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fit_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('validation_status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('email_status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('email_draft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('family_office_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('designation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_approved_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('followup_stage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('followup_status', sa.TEXT(), server_default=sa.text("'IDLE'::text"), autoincrement=False, nullable=True),
    sa.Column('is_responded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_unsubscribed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('manual_entry', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_enriched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_outreach_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rocketreach_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmail_thread_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reply_intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meeting_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meeting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deal_size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pitch_deck_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rag_advice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmail_draft_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('urgency_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rag_intelligence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('lead_type', sa.TEXT(), server_default=sa.text("'INVESTOR'::text"), autoincrement=False, nullable=True),
    sa.Column('intent_level', sa.TEXT(), server_default=sa.text("'Low'::text"), autoincrement=False, nullable=True),
    sa.Column('ai_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('system_confidence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('cc_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_draft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_outreach_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_outreach_subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmail_message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_outreach_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_outreach_subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('draft_template_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('check_size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_opt_in', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('unsubscribe_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('replied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pipeline_state', sa.TEXT(), server_default=sa.text("'NEW'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_raw_pkey'))
    )
    op.create_index(op.f('leads_raw_email_user_unique'), 'leads_raw', ['email', sa.literal_column("COALESCE(user_id, '-1'::integer)")], unique=True)
    op.create_index(op.f('idx_leads_raw_user_id'), 'leads_raw', ['user_id'], unique=False)
    op.create_index(op.f('idx_leads_raw_updated_at'), 'leads_raw', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_leads_raw_unsubscribe_token'), 'leads_raw', ['unsubscribe_token'], unique=False)
    op.create_index(op.f('idx_leads_raw_pipeline_state'), 'leads_raw', ['pipeline_state'], unique=False)
    op.create_index(op.f('idx_leads_raw_lower_email'), 'leads_raw', [sa.literal_column('lower(email)')], unique=False)
    op.create_index(op.f('idx_leads_raw_last_outreach'), 'leads_raw', [sa.literal_column('last_outreach_at DESC')], unique=False)
    op.create_index(op.f('idx_leads_raw_followup_status'), 'leads_raw', ['followup_status'], unique=False)
    op.create_index(op.f('idx_leads_raw_email_status_user'), 'leads_raw', ['email_status', 'user_id'], unique=False)
    op.create_index(op.f('idx_leads_raw_email_status'), 'leads_raw', ['email_status'], unique=False)
    op.create_table('org_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('default_cc', sa.TEXT(), server_default=sa.text("'lalit.h@qvscl.com'::text"), autoincrement=False, nullable=True),
    sa.Column('vismaya_cc', sa.TEXT(), server_default=sa.text("'rajesh.s@qvscl.com'::text"), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), server_default=sa.text("'https://qvscl.com'::text"), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), server_default=sa.text("'https://linkedin.com/company/qvscl'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('org_settings_pkey'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tone', sa.TEXT(), server_default=sa.text("'professional'::text"), autoincrement=False, nullable=True),
    sa.Column('target_industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_persona', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('html_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strategy_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('target_companies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('campaigns_pkey')),
    sa.UniqueConstraint('name', name=op.f('campaigns_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('followup_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING_APPROVAL'::text"), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], name=op.f('followup_schedules_lead_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('followup_schedules_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('followup_schedules_pkey'))
    )
    op.create_table('reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'MEDIUM'::text"), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reminders_pkey'))
    )
    op.create_table('sector_strategies',
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('strategy', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sector', name=op.f('sector_strategies_pkey'))
    )
    op.create_table('app_settings',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    op.create_table('company_registry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('_is_generated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('company_registry_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_registry_pkey'))
    )
    op.create_index(op.f('idx_company_registry_email'), 'company_registry', [sa.literal_column("(row_data ->> 'Email'::text)")], unique=False)
    op.create_index(op.f('company_registry_user_id'), 'company_registry', ['user_id'], unique=False)
    op.create_index(op.f('company_registry_user_email_unique'), 'company_registry', ['user_id', sa.literal_column("(row_data ->> 'Email'::text)")], unique=True)
    op.create_index(op.f('company_registry_source_tab'), 'company_registry', [sa.literal_column("(row_data ->> '_source_tab'::text)")], unique=False)
    op.create_index(op.f('company_registry_is_generated'), 'company_registry', ['_is_generated'], unique=False)
    op.create_table('user_signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), server_default=sa.text("'My Signature'::character varying"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('attachment_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sig_type', sa.TEXT(), server_default=sa.text("'outreach'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_signatures_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_signatures_pkey'))
    )
    op.create_index(op.f('idx_user_signatures_user_id'), 'user_signatures', ['user_id'], unique=False)
    op.create_table('email_idempotency',
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('email_idempotency_pkey'))
    )
    op.create_index(op.f('idx_email_idempotency_expires'), 'email_idempotency', ['expires_at'], unique=False)
    op.create_table('gmail_processed_messages',
    sa.Column('message_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('message_id', name=op.f('gmail_processed_messages_pkey'))
    )
    op.create_table('email_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gmail_message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('clicked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('email_events_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], name=op.f('email_events_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_events_pkey'))
    )
    op.create_table('activity_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    op.create_index(op.f('idx_activity_log_lead_id'), 'activity_log', ['lead_id'], unique=False)
    op.create_index(op.f('idx_activity_log_created_at'), 'activity_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_activity_log_action_user'), 'activity_log', ['action', 'user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outreach_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('template_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_draft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('followup_status', sa.TEXT(), server_default=sa.text("'IDLE'::text"), autoincrement=False, nullable=True),
    sa.Column('followup_stage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_responded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('gmail_thread_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmail_message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmail_draft_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tracking_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reply_intent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deal_size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('replied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], name=op.f('outreach_records_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('outreach_records_pkey'))
    )
    op.create_index(op.f('idx_outreach_status'), 'outreach_records', ['lead_id', 'email_status', 'followup_status'], unique=False)
    op.create_index(op.f('idx_outreach_lead'), 'outreach_records', ['lead_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=True),
    sa.Column('tracking_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('recipients_campaign_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], name=op.f('recipients_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recipients_pkey')),
    sa.UniqueConstraint('tracking_token', name=op.f('recipients_tracking_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    sa.UniqueConstraint('token', name=op.f('sessions_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sessions_token'), 'sessions', ['token'], unique=False)
    op.create_table('unsubscribe_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unsubscribe_list_pkey')),
    sa.UniqueConstraint('email', name=op.f('unsubscribe_list_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('email_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unsubscribe_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('marketing_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('transactional_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'subscribed'::character varying"), autoincrement=False, nullable=True),
    sa.Column('unsubscribe_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_raw.id'], name=op.f('email_preferences_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_preferences_pkey')),
    sa.UniqueConstraint('unsubscribe_token', name=op.f('email_preferences_unsubscribe_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'USER'::text"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('has_db_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('credits_limit', sa.INTEGER(), server_default=sa.text('200'), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('google_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('google_linked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_gmail_history_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_followup', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('outreach_daily_limit', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True),
    sa.Column('team', sa.TEXT(), server_default=sa.text("'CLIENT'::text"), autoincrement=False, nullable=True),
    sa.Column('signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signature_mode', sa.TEXT(), server_default=sa.text("'custom'::text"), autoincrement=False, nullable=True),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_font', sa.TEXT(), server_default=sa.text("'sans-serif'::text"), autoincrement=False, nullable=True),
    sa.Column('email_font_size', sa.TEXT(), server_default=sa.text("'15px'::text"), autoincrement=False, nullable=True),
    sa.Column('signature_font', sa.TEXT(), server_default=sa.text("'sans-serif'::text"), autoincrement=False, nullable=True),
    sa.Column('signature_font_size', sa.TEXT(), server_default=sa.text("'13px'::text"), autoincrement=False, nullable=True),
    sa.Column('image_width', sa.TEXT(), server_default=sa.text("'400px'::text"), autoincrement=False, nullable=True),
    sa.Column('image_height', sa.TEXT(), server_default=sa.text("'auto'::text"), autoincrement=False, nullable=True),
sa.Column('auto_pilot_drafts', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('campaign_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_events_campaign_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('campaign_events_recipient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_events_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all tables."""
    op.drop_table('campaign_events')
    op.drop_table('users')
    op.drop_table('email_preferences')
    op.drop_table('unsubscribe_list')
    op.drop_index(op.f('idx_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('recipients')
    op.drop_index(op.f('idx_outreach_lead'), table_name='outreach_records')
    op.drop_index(op.f('idx_outreach_status'), table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_index(op.f('idx_activity_log_action_user'), table_name='activity_log')
    op.drop_index(op.f('idx_activity_log_created_at'), table_name='activity_log')
    op.drop_index(op.f('idx_activity_log_lead_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('email_events')
    op.drop_table('gmail_processed_messages')
    op.drop_index(op.f('idx_email_idempotency_expires'), table_name='email_idempotency')
    op.drop_table('email_idempotency')
    op.drop_index(op.f('idx_user_signatures_user_id'), table_name='user_signatures')
    op.drop_table('user_signatures')
    op.drop_index(op.f('company_registry_is_generated'), table_name='company_registry')
    op.drop_index(op.f('company_registry_source_tab'), table_name='company_registry')
    op.drop_index(op.f('company_registry_user_email_unique'), table_name='company_registry')
    op.drop_index(op.f('company_registry_user_id'), table_name='company_registry')
    op.drop_index(op.f('idx_company_registry_email'), table_name='company_registry')
    op.drop_table('company_registry')
    op.drop_table('app_settings')
    op.drop_table('sector_strategies')
    op.drop_table('reminders')
    op.drop_table('followup_schedules')
    op.drop_table('campaigns')
    op.drop_table('org_settings')
    op.drop_index(op.f('leads_raw_email_user_unique'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_user_id'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_updated_at'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_unsubscribe_token'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_pipeline_state'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_lower_email'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_last_outreach'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_followup_status'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_email_status_user'), table_name='leads_raw')
    op.drop_index(op.f('idx_leads_raw_email_status'), table_name='leads_raw')
    op.drop_table('leads_raw')
    op.drop_table('prompts')
    op.drop_table('family_offices')
    op.drop_table('gsheet_sync_configs')